name: Validate Renovate Config
on: [push, pull_request]

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@main
        with:
          node-version-file: package.json

      - name: Validate renovate config
        run: npx --package renovate -c 'renovate-config-validator'
