name: Validate Renovate Config
on: [push, pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@main
        with:
          node-version-file: package.json

      - name: Validate Renovate Config
        run: RENOVATE_CONFIG_FILE=default.json npx --yes --package renovate -- renovate-config-validator --strict
